server:
  port: 8080
spring:
  application:
    name: bye-crud-generate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/mall-pro?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
bycrud:
  ## 模板路径
  source:
    entity: generate/entity.java.vm
    controller: generate/controller.java.vm
    mapper: generate/mapper.java.vm
    mapping: generate/mapping.xml.vm
    service: generate/service.java.vm
    serviceImpl: generate/serviceImpl.java.vm
    saveAO: generate/saveAO.java.vm
    pageAO: generate/pageAO.java.vm
  packages:
    entity: model
    mapping: mapper
    controller: controller
    service: service
    serviceImpl: service.impl
    saveAO: pojo
    pageAO: pojo
  type:
    char: String
    varchar: String
    text: String
    int: Integer
    tinyint: Integer
    date: Date
    datetime: Date
    timestamp: Date
    bigint: Long
  prefix:
    controller: Api
  suffix:
    entity: Model
    saveAO: SaveAO
    pageAO: PageAO
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true